# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "05e0c49b2087210e8071924386ef53e4"
application_url = "https://date-equilibrium-observations-representations.trycloudflare.com"
embedded = true
name = "varify-io"
handle = "varify-io-3"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "varify-a-b-testing.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,write_pixels"

[auth]
redirect_urls = [
  "https://date-equilibrium-observations-representations.trycloudflare.com/auth/callback",
  "https://date-equilibrium-observations-representations.trycloudflare.com/auth/shopify/callback",
  "https://date-equilibrium-observations-representations.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
