# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fc9305b77355d776c64db4fe678764e2"
application_url = "https://ecommerce.varify.io"
embedded = true
name = "Varify - A/B Testing"
handle = "varify-a-b-testing"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "varify-io.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,write_pixels"

[auth]
redirect_urls = [
  "https://ecommerce.varify.io/auth/callback",
  "https://ecommerce.varify.io/auth/shopify/callback",
  "https://ecommerce.varify.io/api/auth/callback"
]

[pos]
embedded = false

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request"]
uri = "/webhooks"

[[webhooks.subscriptions]]
compliance_topics = ["customers/redact"]
uri = "/webhooks"

[[webhooks.subscriptions]]
compliance_topics = ["shop/redact"]
uri = "/webhooks"
