# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fc9305b77355d776c64db4fe678764e2"
application_url = "https://7eb4-2401-4900-8899-74bc-5038-682e-a774-aa33.ngrok-free.app"
embedded = true
name = "Varify - A/B Testing"
handle = "varify-a-b-testing"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "varify-io.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,write_pixels"

[auth]
redirect_urls = [
  "https://7eb4-2401-4900-8899-74bc-5038-682e-a774-aa33.ngrok-free.app/auth/callback",
  "https://7eb4-2401-4900-8899-74bc-5038-682e-a774-aa33.ngrok-free.app/auth/shopify/callback",
  "https://7eb4-2401-4900-8899-74bc-5038-682e-a774-aa33.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false
